{% set version = "3.3.1" %}

package:
  name: triqs_dft_tools
  version: {{ version }}

source:
  url: https://github.com/TRIQS/dft_tools/releases/download/{{ version }}/dft_tools-{{ version }}.tar.gz
  sha256: f4a9b9d44769fb7fe06892640217a915d133845169eae2fe450a41974c4b47c3

build:
  number: 2
  skip: true  # [win or py<30]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}                              # [mpi == 'openmpi' and build_platform != target_platform]
    - meson        # [py>=312]
    - setuptools   # [py>=312]
    - ninja        # [py>=312]
  host:
    - triqs {{ '.'.join(version.split('.')[:2]) }}
    - libboost-headers
    - {{ mpi }}
    - libblas
    - liblapack
    - numpy
    - python
  run:
    - {{ pin_compatible("triqs", max_pin="x.x") }}
    - {{ mpi }}
    - libblas
    - liblapack
    - python

test:
  commands:
    - export OMPI_MCA_btl=self,tcp
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export mpiexec="mpiexec --allow-run-as-root"
    - python -c "import triqs_dft_tools"

about:
  home: https://triqs.github.io/dft_tools
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Toolbox for ab initio calculations of correlated materials

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
    - thoemi09
